Added a check to see if python is installed
Python3 is now a requirement to build the code.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18,8 +18,8 @@ HAVE_OBSTACK=1
 VERSION=$(git describe --abbrev=0)
 VERSION=${VERSION:1}
 INDENT=40
-ok="${GREEN}OK$NORMAL"
-fail="${RED}FAIL$NORMAL"
+OK="${GREEN}OK$NORMAL"
+FAIL="${RED}FAIL$NORMAL"
 
 usage()
 {
@@ -42,7 +42,7 @@ check_gcc()
     $CC "$BUILD.c" -o "$BUILD" &> /dev/null
 
     if [ ! -x "$BUILD" ]; then
-        printf "[$fail]\n\n"
+        printf "[$FAIL]\n\n"
         if [[ $CC == "gcc" || $CC == "clang" ]]; then
             printf "You need a functioning install of $CC. "
             printf "This can be installed with \"pacman -S $CC\" or equivalent "
@@ -53,7 +53,7 @@ check_gcc()
     fi
 
     rm -f "$BUILD.c" "$BUILD"
-    printf "[$ok]\n"
+    printf "[$OK]\n"
 }
 
 check_ncurses()
@@ -64,7 +64,7 @@ check_ncurses()
     $CC "$BUILD.c" -o "$BUILD" -lncurses &> /dev/null
 
     if [ ! -x "$BUILD" ]; then
-        printf "[$fail]\n\n"
+        printf "[$FAIL]\n\n"
         printf "You need a functioning install of libncurses. "
         printf "This can be installed with \"pacman -S ncurses\" or equivalent "
         printf "command for your distribution.\n"
@@ -73,7 +73,7 @@ check_ncurses()
     fi
 
     rm -f "$BUILD.c" "$BUILD"
-    printf "[$ok]\n"
+    printf "[$OK]\n"
 }
 
 check_geoip()
@@ -91,7 +91,7 @@ EOF
     $CC "$BUILD.c" -o "$BUILD" -lGeoIP  &> /dev/null
 
     if [ ! -x "$BUILD" ]; then
-        printf "[$fail]\n\n"
+        printf "[$FAIL]\n\n"
         printf "You need a functioning install of libGeoIP. "
         printf "This can be installed with \"pacman -S geoip geoip-database "
         printf "geoip-database-extra\" or equivalent command for your distribution.\n"
@@ -100,7 +100,7 @@ EOF
     fi
 
     rm -f "$BUILD.c" "$BUILD"
-    printf "[$ok]\n"
+    printf "[$OK]\n"
 }
 
 check_re2c()
@@ -109,13 +109,26 @@ check_re2c()
 
     command -v re2c >/dev/null ||
         {
-            printf "[$fail]\n\n"
+            printf "[$FAIL]\n\n"
             printf "re2c needs to be installed. This can be installed with ";
             printf "\"pacman -S re2c\" or equivalent command for your distribution.\n";
             exit 1;
         }
-    printf "[$ok]\n"
- }
+    printf "[$OK]\n"
+}
+
+check_python3()
+{
+    printf "[*] %-*s" "$INDENT" "Checking for python3... "
+    command -v python3 >/dev/null ||
+        {
+            printf "[$FAIL]\n\n"
+            printf "python3 needs to be installed. This can be installed with ";
+            printf "\"pacman -S python\" or equivalent command for your distribution.\n";
+            exit 1;
+        }
+    printf "[$OK]\n"
+}
 
 check_missing()
 {
@@ -180,5 +193,6 @@ if [[ "$HAVE_GEOIP" == 1 ]]; then
     check_geoip
 fi
 check_re2c
+check_python3
 check_missing
 generate_config
