Drop the dependency on pkgconf from configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,29 +1,38 @@
 #!/bin/bash
 
 DISABLE_GEOIP=0
+CC="gcc"
+GEOIP_PATH="/usr/share/GeoIP/GeoIPCity.dat"
+BUILD=".build_$$"
 
 usage()
 {
     echo "Usage: ./configure [option]"
     echo ""
-    echo "   --disable-geoip  : Build without libGeoIP"
-    echo "   -h --help        : Display help"
+    echo "   --disable-geoip         : Build without libGeoIP"
+    echo "   --set-geoip-path <path> : Set the default GeoIP path"
+    echo "   -h, --help              : Display help"
     exit 0
 }
 
-check_pkgconf()
+check_gcc()
 {
-    echo -n "[*] Checking for pkgconf... "
+    echo -n "[*] Checking for gcc... "
 
-    command -v pkgconf >/dev/null ||
-        {
-            echo "FAIL";
-            echo;
-            echo -n "pkgconf needs to be installed. This can be installed with ";
-            echo "\"pacman -S pkgconf\" or equivalent command for your distribution.";
-            exit 1;
-        }
+    echo "int main() { return 0; }" > "$BUILD.c"
+    $CC "$BUILD.c" -o "$BUILD" &> /dev/null
 
+    if [ ! -x "$BUILD" ]; then
+        echo "FAIL";
+        echo;
+        echo -n "You need a functioning install of gcc."
+        echo -n "This can be installed with \"pacman -S gcc\" or equivalent "
+        echo "command for your distribution."
+        rm -f "$BUILD.c" "$BUILD"
+        exit 1;
+    fi
+
+    rm -f "$BUILD.c" "$BUILD"
     echo "OK"
 }
 
@@ -31,15 +40,20 @@ check_ncurses()
 {
     echo -n "[*] Checking for libncurses... "
 
-    if ! $(pkgconf --exists ncurses); then
+    echo -e "#include <ncurses.h>\nint main() { initscr(); endwin(); }" > "$BUILD.c"
+    $CC "$BUILD.c" -o "$BUILD" -lncurses &> /dev/null
+
+    if [ ! -x "$BUILD" ]; then
         echo "FAIL"
         echo
         echo -n "You need a functioning install of libncurses. "
         echo -n "This can be installed with \"pacman -S ncurses\" or equivalent "
         echo "command for your distribution."
+        rm -f "$BUILD.c" "$BUILD"
         exit 1
     fi
 
+    rm -f "$BUILD.c" "$BUILD"
     echo "OK"
 }
 
@@ -47,15 +61,20 @@ check_geoip()
 {
     echo -n "[*] Checking for libGeoIP... "
 
-    if ! $(pkgconf --exists geoip); then
+    echo -e "#include <GeoIP.h>\nint main() { GeoIP *gip = GeoIP_open(\"$GEOIP_PATH\", GEOIP_STANDARD); GeoIP_delete(gip); }" >"$BUILD.c"
+    $CC "$BUILD.c" -o "$BUILD" -lGeoIP &> /dev/null
+
+    if [ ! -x "$BUILD" ]; then
         echo "FAIL"
         echo
         echo -n "You need a functioning install of libGeoIP. "
         echo -n "This can be installed with \"pacman -S geoip geoip-database "
         echo "geoip-database-extra\" or equivalent command for your distribution."
+        rm -f "$BUILD.c" "$BUILD"
         exit 1
     fi
 
+    rm -f "$BUILD.c" "$BUILD"
     echo "OK"
 }
 
@@ -72,6 +91,7 @@ generate_config()
         echo "CONFIG_GEOIP=0" >> config.mk
     else
         echo "#define HAVE_GEOIP 1" >> config.h
+        echo "#define GEOIP_PATH \"$GEOIP_PATH\"" >> config.h
         echo "CONFIG_GEOIP=1" >> config.mk
     fi
 
@@ -87,6 +107,10 @@ while [ $# -gt 0 ]; do
         --disable-geoip)
             DISABLE_GEOIP=1
             ;;
+        --set-geoip-path)
+            shift
+            GEOIP_PATH=$1
+            ;;
         *)
             echo "Invalid option. Use -h for help"
             exit 1;
@@ -95,7 +119,7 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-check_pkgconf
+check_gcc
 check_ncurses
 if [[ "$DISABLE_GEOIP" == 0 ]]; then
     check_geoip
